ALTER TABLE ALUMNO_ASIGNATURA_PERIODO 
   DROP FOREIGN KEY FK_ALUMNO_A_REFERENCE_MATRICUL;

ALTER TABLE ALUMNO_ASIGNATURA_PERIODO 
   DROP FOREIGN KEY FK_ALUMNO_A_REFERENCE_ASIGNATU;

ALTER TABLE ASIGNATURA 
   DROP FOREIGN KEY FK_ASIGNATU_ASIGANTUR_NIVEL_ED;

ALTER TABLE ASIGNATURA_PERIODO 
   DROP FOREIGN KEY FK_ASIGNATU_REFERENCE_ASIGNATU;

ALTER TABLE ASIGNATURA_PERIODO 
   DROP FOREIGN KEY FK_ASIGNATU_REFERENCE_PERIODO_;

ALTER TABLE ASIGNATURA_PERIODO 
   DROP FOREIGN KEY FK_ASIGNATU_REFERENCE_PARALELO;

ALTER TABLE ASIGNATURA_PERIODO 
   DROP FOREIGN KEY FK_ASIGNATU_REFERENCE_PERSONA;

ALTER TABLE ASISTENCIA_PERIODO 
   DROP FOREIGN KEY FK_ASISTENC_REFERENCE_MATRICUL;

ALTER TABLE AULA 
   DROP FOREIGN KEY FK_AULA_AULA_A_ED_EDIFICIO;

ALTER TABLE CALIFICACION_PRUEBA_ASPIRANTE 
   DROP FOREIGN KEY FK_CALIFICA_ASPIRANTE_ASPIRANT;

ALTER TABLE CALIFICACION_PRUEBA_ASPIRANTE 
   DROP FOREIGN KEY FK_CALIFICA_NIVEL_EDU_NIVEL_ED;

ALTER TABLE COMUNICADO_ASIGNATURA 
   DROP FOREIGN KEY FK_COMUNICA_REFERENCE_ASIGNATU;

ALTER TABLE CRONOGRAMA_PERIODO 
   DROP FOREIGN KEY FK_CRONOGRA_CRONOGRAM_PERIODO_;

ALTER TABLE EDIFICIO 
   DROP FOREIGN KEY FK_EDIFICIO_EDIFICIO__SEDE;

ALTER TABLE MATRICULA_PERIODO 
   DROP FOREIGN KEY FK_MATRICUL_REFERENCE_PERIODO_;

ALTER TABLE MATRICULA_PERIODO 
   DROP FOREIGN KEY FK_MATRICUL_REFERENCE_PERSONA;

ALTER TABLE MATRICULA_PERIODO 
   DROP FOREIGN KEY FK_MATRICUL_REFERENCE_NIVEL_ED;

ALTER TABLE PARALELO 
   DROP FOREIGN KEY FK_PARALELO_REFERENCE_NIVEL_ED;

ALTER TABLE PERSONA 
   DROP FOREIGN KEY FK_PERSONA_PERSONA_A_PERSONA;

ALTER TABLE REGLA_PERIODO 
   DROP FOREIGN KEY FK_REGLA_PE_REGLAPER__PERIODO_;

ALTER TABLE ROL_USUARIO 
   DROP FOREIGN KEY FK_ROL_USUA_ROLUSU_A__ROL;

ALTER TABLE ROL_USUARIO 
   DROP FOREIGN KEY FK_ROL_USUA_ROLUSU_A__USUARIO;

ALTER TABLE TIPO_PERSONA_PERSONA 
   DROP FOREIGN KEY FK_TIPO_PER_TIPOPERPE_TIPO_PER;

ALTER TABLE TIPO_PERSONA_PERSONA 
   DROP FOREIGN KEY FK_TIPO_PER_TIPOPER_A_PERSONA;

ALTER TABLE USUARIO 
   DROP FOREIGN KEY FK_USUARIO_USUARIO_A_PERSONA;


alter table ALUMNO_ASIGNATURA_PERIODO 
   drop foreign key FK_ALUMNO_A_REFERENCE_MATRICUL;

alter table ALUMNO_ASIGNATURA_PERIODO 
   drop foreign key FK_ALUMNO_A_REFERENCE_ASIGNATU;

DROP TABLE IF EXISTS ALUMNO_ASIGNATURA_PERIODO;


alter table ASIGNATURA 
   drop foreign key FK_ASIGNATU_ASIGANTUR_NIVEL_ED;

DROP TABLE IF EXISTS ASIGNATURA;


alter table ASIGNATURA_PERIODO 
   drop foreign key FK_ASIGNATU_REFERENCE_ASIGNATU;

alter table ASIGNATURA_PERIODO 
   drop foreign key FK_ASIGNATU_REFERENCE_PERIODO_;

alter table ASIGNATURA_PERIODO 
   drop foreign key FK_ASIGNATU_REFERENCE_PARALELO;

alter table ASIGNATURA_PERIODO 
   drop foreign key FK_ASIGNATU_REFERENCE_PERSONA;

DROP TABLE IF EXISTS ASIGNATURA_PERIODO;


alter table ASISTENCIA_PERIODO 
   drop foreign key FK_ASISTENC_REFERENCE_MATRICUL;

DROP TABLE IF EXISTS ASISTENCIA_PERIODO;

DROP TABLE IF EXISTS ASPIRANTE;


alter table AULA 
   drop foreign key FK_AULA_AULA_A_ED_EDIFICIO;

DROP TABLE IF EXISTS AULA;


alter table CALIFICACION_PRUEBA_ASPIRANTE 
   drop foreign key FK_CALIFICA_NIVEL_EDU_NIVEL_ED;

alter table CALIFICACION_PRUEBA_ASPIRANTE 
   drop foreign key FK_CALIFICA_ASPIRANTE_ASPIRANT;

DROP TABLE IF EXISTS CALIFICACION_PRUEBA_ASPIRANTE;


alter table COMUNICADO_ASIGNATURA 
   drop foreign key FK_COMUNICA_REFERENCE_ASIGNATU;

DROP TABLE IF EXISTS COMUNICADO_ASIGNATURA;


alter table CRONOGRAMA_PERIODO 
   drop foreign key FK_CRONOGRA_CRONOGRAM_PERIODO_;

DROP TABLE IF EXISTS CRONOGRAMA_PERIODO;


alter table EDIFICIO 
   drop foreign key FK_EDIFICIO_EDIFICIO__SEDE;

DROP TABLE IF EXISTS EDIFICIO;


alter table MATRICULA_PERIODO 
   drop foreign key FK_MATRICUL_REFERENCE_PERIODO_;

alter table MATRICULA_PERIODO 
   drop foreign key FK_MATRICUL_REFERENCE_PERSONA;

alter table MATRICULA_PERIODO 
   drop foreign key FK_MATRICUL_REFERENCE_NIVEL_ED;

DROP TABLE IF EXISTS MATRICULA_PERIODO;

DROP TABLE IF EXISTS NIVEL_EDUCATIVO;


alter table PARALELO 
   drop foreign key FK_PARALELO_REFERENCE_NIVEL_ED;

DROP TABLE IF EXISTS PARALELO;

DROP TABLE IF EXISTS PERIODO_LECTIVO;

DROP INDEX IDXU_PERSONA_CEDULA ON PERSONA;


alter table PERSONA 
   drop foreign key FK_PERSONA_PERSONA_A_PERSONA;

DROP TABLE IF EXISTS PERSONA;


alter table REGLA_PERIODO 
   drop foreign key FK_REGLA_PE_REGLAPER__PERIODO_;

DROP TABLE IF EXISTS REGLA_PERIODO;

DROP TABLE IF EXISTS ROL;


alter table ROL_USUARIO 
   drop foreign key FK_ROL_USUA_ROLUSU_A__ROL;

alter table ROL_USUARIO 
   drop foreign key FK_ROL_USUA_ROLUSU_A__USUARIO;

DROP TABLE IF EXISTS ROL_USUARIO;

DROP TABLE IF EXISTS SEDE;

DROP TABLE IF EXISTS TIPO_PERSONA;


alter table TIPO_PERSONA_PERSONA 
   drop foreign key FK_TIPO_PER_TIPOPERPE_TIPO_PER;

alter table TIPO_PERSONA_PERSONA 
   drop foreign key FK_TIPO_PER_TIPOPER_A_PERSONA;

DROP TABLE IF EXISTS TIPO_PERSONA_PERSONA;

DROP INDEX IDXU_USUARIO_NOMBREUSUARIO ON USUARIO;


alter table USUARIO 
   drop foreign key FK_USUARIO_USUARIO_A_PERSONA;

DROP TABLE IF EXISTS USUARIO;

/*==============================================================*/
/* Table: ALUMNO_ASIGNATURA_PERIODO                             */
/*==============================================================*/
CREATE TABLE ALUMNO_ASIGNATURA_PERIODO
(
   COD_PERIODO_LECTIVO  VARCHAR(12)  COMMENT '',
   COD_NIVEL_EDUCATIVO  VARCHAR(8)  COMMENT '',
   COD_ASIGNATURA       VARCHAR(8)  COMMENT '',
   COD_PARALELO         VARCHAR(8)  COMMENT '',
   COD_DOCENTE          INT  COMMENT '',
   MAT_COD_PERIODO_LECTIVO VARCHAR(12)  COMMENT '',
   COD_ALUMNO           INT  COMMENT '',
   MAT_COD_NIVEL_EDUCATIVO VARCHAR(8)  COMMENT '',
   NOTA1                NUMERIC(4,2)  COMMENT '',
   NOTA2                NUMERIC(4,2)  COMMENT '',
   NOTA3                NUMERIC(4,2)  COMMENT '',
   NOTA4                NUMERIC(4,2)  COMMENT '',
   NOTA5                NUMERIC(4,2)  COMMENT '',
   NOTA6                NUMERIC(4,2)  COMMENT '',
   NOTA7                NUMERIC(4,2)  COMMENT '',
   NOTA8                NUMERIC(4,2)  COMMENT '',
   NOTA9                NUMERIC(4,2)  COMMENT '',
   NOTA10               NUMERIC(4,2)  COMMENT '',
   NOTA11               NUMERIC(4,2)  COMMENT '',
   NOTA12               NUMERIC(4,2)  COMMENT '',
   NOTA13               NUMERIC(4,2)  COMMENT '',
   NOTA14               NUMERIC(4,2)  COMMENT '',
   NOTA15               NUMERIC(4,2)  COMMENT ''
);

/*==============================================================*/
/* Table: ASIGNATURA                                            */
/*==============================================================*/
CREATE TABLE ASIGNATURA
(
   COD_NIVEL_EDUCATIVO  VARCHAR(8) NOT NULL  COMMENT '',
   COD_ASIGNATURA       VARCHAR(8) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(100) NOT NULL  COMMENT '',
   CREDITOS             NUMERIC(2) NOT NULL  COMMENT '',
   TIPO                 VARCHAR(3) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA)
);

/*==============================================================*/
/* Table: ASIGNATURA_PERIODO                                    */
/*==============================================================*/
CREATE TABLE ASIGNATURA_PERIODO
(
   COD_NIVEL_EDUCATIVO  VARCHAR(8) NOT NULL  COMMENT '',
   COD_ASIGNATURA       VARCHAR(8) NOT NULL  COMMENT '',
   COD_PERIODO_LECTIVO  VARCHAR(12) NOT NULL  COMMENT '',
   COD_PARALELO         VARCHAR(8) NOT NULL  COMMENT '',
   COD_DOCENTE          INT NOT NULL  COMMENT '',
   PRIMARY KEY (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA, COD_PERIODO_LECTIVO, COD_PARALELO, COD_DOCENTE)
);

/*==============================================================*/
/* Table: ASISTENCIA_PERIODO                                    */
/*==============================================================*/
CREATE TABLE ASISTENCIA_PERIODO
(
   COD_PERIODO_LECTIVO  VARCHAR(12) NOT NULL  COMMENT '',
   COD_ALUMNO           INT NOT NULL  COMMENT '',
   COD_NIVEL_EDUCATIVO  VARCHAR(8) NOT NULL  COMMENT '',
   FECHA                DATE NOT NULL  COMMENT '',
   ESTADO               VARCHAR(3)  COMMENT '',
   PRIMARY KEY (COD_PERIODO_LECTIVO, COD_ALUMNO, COD_NIVEL_EDUCATIVO, FECHA)
);

/*==============================================================*/
/* Table: ASPIRANTE                                             */
/*==============================================================*/
CREATE TABLE ASPIRANTE
(
   COD_ASPIRANTE        INT NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(32) NOT NULL  COMMENT '',
   APELLIDO             VARCHAR(32) NOT NULL  COMMENT '',
   CEDULA               VARCHAR(10) NOT NULL  COMMENT '',
   TELEFONO             VARCHAR(15)  COMMENT '',
   FECHA_NACIMIENTO     DATE NOT NULL  COMMENT '',
   GENERO               VARCHAR(3) NOT NULL  COMMENT '',
   CORREO               VARCHAR(128) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_ASPIRANTE)
);

/*==============================================================*/
/* Table: AULA                                                  */
/*==============================================================*/
CREATE TABLE AULA
(
   COD_AULA             VARCHAR(8) NOT NULL  COMMENT '',
   COD_EDIFICIO         VARCHAR(8) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(100) NOT NULL  COMMENT '',
   CAPACIDAD            NUMERIC(3) NOT NULL  COMMENT '',
   TIPO                 VARCHAR(3) NOT NULL DEFAULT 'GEN'  COMMENT '',
   PISO                 NUMERIC(2) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_AULA)
);

/*==============================================================*/
/* Table: CALIFICACION_PRUEBA_ASPIRANTE                         */
/*==============================================================*/
CREATE TABLE CALIFICACION_PRUEBA_ASPIRANTE
(
   COD_CALIFICACION_PREBA_ASPIRANTE VARCHAR(8) NOT NULL  COMMENT '',
   COD_NIVEL_EDUCATIVO  VARCHAR(8)  COMMENT '',
   COD_ASPIRANTE        INT  COMMENT '',
   FECHA_PRUEBA         DATE NOT NULL  COMMENT '',
   CALIFICACION         NUMERIC(4,2) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_CALIFICACION_PREBA_ASPIRANTE)
);

/*==============================================================*/
/* Table: COMUNICADO_ASIGNATURA                                 */
/*==============================================================*/
CREATE TABLE COMUNICADO_ASIGNATURA
(
   COD_NIVEL_EDUCATIVO  VARCHAR(8)  COMMENT '',
   COD_ASIGNATURA       VARCHAR(8)  COMMENT '',
   COD_PERIODO_LECTIVO  VARCHAR(12)  COMMENT '',
   COD_PARALELO         VARCHAR(8)  COMMENT '',
   COD_DOCENTE          INT  COMMENT '',
   KEY AK_PK_COMUNICADO_ASIGNATURA (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA, COD_PERIODO_LECTIVO, COD_PARALELO, COD_DOCENTE)
);

/*==============================================================*/
/* Table: CRONOGRAMA_PERIODO                                    */
/*==============================================================*/
CREATE TABLE CRONOGRAMA_PERIODO
(
   COD_CRONOGRAMA_PERIODO INT NOT NULL AUTO_INCREMENT  COMMENT '',
   COD_PERIODO_LECTIVO  VARCHAR(12) NOT NULL  COMMENT '',
   FECHA                DATE NOT NULL  COMMENT '',
   TIPO                 VARCHAR(3)  COMMENT '',
   DESCRIPCION          VARCHAR(1000)  COMMENT '',
   PRIMARY KEY (COD_CRONOGRAMA_PERIODO)
);

/*==============================================================*/
/* Table: EDIFICIO                                              */
/*==============================================================*/
CREATE TABLE EDIFICIO
(
   COD_EDIFICIO         VARCHAR(8) NOT NULL  COMMENT '',
   COD_SEDE             VARCHAR(6) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(100) NOT NULL  COMMENT '',
   CANTIDAD_PISOS       NUMERIC(2) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_EDIFICIO)
);

/*==============================================================*/
/* Table: MATRICULA_PERIODO                                     */
/*==============================================================*/
CREATE TABLE MATRICULA_PERIODO
(
   COD_PERIODO_LECTIVO  VARCHAR(12) NOT NULL  COMMENT '',
   COD_ALUMNO           INT NOT NULL  COMMENT '',
   COD_NIVEL_EDUCATIVO  VARCHAR(8) NOT NULL  COMMENT '',
   PROMEDIOQ1           NUMERIC(4,2)  COMMENT '',
   PROMEDIOQ2           NUMERIC(4,2)  COMMENT '',
   PROMEDIO_FINAL       NUMERIC(4,2)  COMMENT '',
   PRIMARY KEY (COD_PERIODO_LECTIVO, COD_ALUMNO, COD_NIVEL_EDUCATIVO)
);

/*==============================================================*/
/* Table: NIVEL_EDUCATIVO                                       */
/*==============================================================*/
CREATE TABLE NIVEL_EDUCATIVO
(
   COD_NIVEL_EDUCATIVO  VARCHAR(8) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(100)  COMMENT '',
   NIVEL                VARCHAR(3)  COMMENT '',
   PRIMARY KEY (COD_NIVEL_EDUCATIVO)
);

/*==============================================================*/
/* Table: PARALELO                                              */
/*==============================================================*/
CREATE TABLE PARALELO
(
   COD_PARALELO         VARCHAR(8) NOT NULL  COMMENT '',
   COD_NIVEL_EDUCATIVO  VARCHAR(8)  COMMENT '',
   NOMBRE               VARCHAR(100) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_PARALELO)
);

/*==============================================================*/
/* Table: PERIODO_LECTIVO                                       */
/*==============================================================*/
CREATE TABLE PERIODO_LECTIVO
(
   COD_PERIODO_LECTIVO  VARCHAR(12) NOT NULL  COMMENT '',
   ESTADO               VARCHAR(3) NOT NULL  COMMENT '',
   FECHA_INICIO         DATE NOT NULL  COMMENT '',
   FECHA_FIN            DATE  COMMENT '',
   PRIMARY KEY (COD_PERIODO_LECTIVO)
);

/*==============================================================*/
/* Table: PERSONA                                               */
/*==============================================================*/
CREATE TABLE PERSONA
(
   COD_PERSONA          INT NOT NULL  COMMENT '',
   COD_PERSONA_REPRESENTANTE INT  COMMENT '',
   CEDULA               VARCHAR(10) NOT NULL  COMMENT '',
   APELLIDO             VARCHAR(50) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(50) NOT NULL  COMMENT '',
   DIRECCION            VARCHAR(200) NOT NULL  COMMENT '',
   TELEFONO             VARCHAR(15)  COMMENT '',
   FECHA_NACIMIENTO     DATE NOT NULL  COMMENT '',
   GENERO               VARCHAR(3) NOT NULL  COMMENT '',
   CORREO               VARCHAR(128)  COMMENT '',
   CORREO_PERSONAL      VARCHAR(128) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_PERSONA)
);

/*==============================================================*/
/* Index: IDXU_PERSONA_CEDULA                                   */
/*==============================================================*/
CREATE UNIQUE INDEX IDXU_PERSONA_CEDULA ON PERSONA
(
   CEDULA
);

/*==============================================================*/
/* Table: REGLA_PERIODO                                         */
/*==============================================================*/
CREATE TABLE REGLA_PERIODO
(
   COD_PERIODO_LECTIVO  VARCHAR(12) NOT NULL  COMMENT '',
   COD_REGLA_PERIODO    INT NOT NULL  COMMENT '',
   TIPO                 VARCHAR(3)  COMMENT '',
   NOMBRE_REGLA         VARCHAR(100)  COMMENT '',
   VALOR                VARCHAR(100)  COMMENT '',
   PRIMARY KEY (COD_PERIODO_LECTIVO, COD_REGLA_PERIODO)
);

/*==============================================================*/
/* Table: ROL                                                   */
/*==============================================================*/
CREATE TABLE ROL
(
   COD_ROL              VARCHAR(8) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(100) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_ROL)
);

/*==============================================================*/
/* Table: ROL_USUARIO                                           */
/*==============================================================*/
CREATE TABLE ROL_USUARIO
(
   COD_ROL              VARCHAR(8) NOT NULL  COMMENT '',
   COD_USUARIO          INT NOT NULL  COMMENT '',
   ESTADO               VARCHAR(3) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_ROL, COD_USUARIO)
);

/*==============================================================*/
/* Table: SEDE                                                  */
/*==============================================================*/
CREATE TABLE SEDE
(
   COD_SEDE             VARCHAR(6) NOT NULL  COMMENT '',
   NOMBRE               VARCHAR(100)  COMMENT '',
   DIRECCION            VARCHAR(200)  COMMENT '',
   TELEFONO             VARCHAR(15)  COMMENT '',
   CODIGO_POSTAL        VARCHAR(6)  COMMENT '',
   PRIMARY KEY (COD_SEDE)
);

/*==============================================================*/
/* Table: TIPO_PERSONA                                          */
/*==============================================================*/
CREATE TABLE TIPO_PERSONA
(
   COD_TIPO_PERSONA     VARCHAR(8) NOT NULL  COMMENT '',
   DESCRIPCION          VARCHAR(100) NOT NULL  COMMENT '',
   PRIMARY KEY (COD_TIPO_PERSONA)
);

/*==============================================================*/
/* Table: TIPO_PERSONA_PERSONA                                  */
/*==============================================================*/
CREATE TABLE TIPO_PERSONA_PERSONA
(
   COD_TIPO_PERSONA     VARCHAR(8) NOT NULL  COMMENT '',
   COD_PERSONA          INT NOT NULL  COMMENT '',
   ESTADO               VARCHAR(3) NOT NULL DEFAULT 'ACT'  COMMENT '',
   FECHA_INICIO         DATE NOT NULL  COMMENT '',
   FECH_FIN             DATE  COMMENT '',
   PRIMARY KEY (COD_TIPO_PERSONA, COD_PERSONA)
);

/*==============================================================*/
/* Table: USUARIO                                               */
/*==============================================================*/
CREATE TABLE USUARIO
(
   COD_USUARIO          INT NOT NULL  COMMENT '',
   COD_PERSONA          INT NOT NULL  COMMENT '',
   NOMBRE_USUARIO       VARCHAR(32) NOT NULL  COMMENT '',
   CLAVE                VARCHAR(64) NOT NULL  COMMENT '',
   ESTADO               VARCHAR(3) NOT NULL DEFAULT 'ACT'  COMMENT '',
   ULT_FECHA_INGRESO    DATETIME  COMMENT '',
   INTENTOS_FALLIDOS    NUMERIC(2) NOT NULL DEFAULT 0  COMMENT '',
   PRIMARY KEY (COD_USUARIO)
);

/*==============================================================*/
/* Index: IDXU_USUARIO_NOMBREUSUARIO                            */
/*==============================================================*/
CREATE INDEX IDXU_USUARIO_NOMBREUSUARIO ON USUARIO
(
   NOMBRE_USUARIO
);

ALTER TABLE ALUMNO_ASIGNATURA_PERIODO ADD CONSTRAINT FK_ALUMNO_A_REFERENCE_MATRICUL FOREIGN KEY (MAT_COD_PERIODO_LECTIVO, COD_ALUMNO, MAT_COD_NIVEL_EDUCATIVO)
      REFERENCES MATRICULA_PERIODO (COD_PERIODO_LECTIVO, COD_ALUMNO, COD_NIVEL_EDUCATIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ALUMNO_ASIGNATURA_PERIODO ADD CONSTRAINT FK_ALUMNO_A_REFERENCE_ASIGNATU FOREIGN KEY (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA, COD_PERIODO_LECTIVO, COD_PARALELO, COD_DOCENTE)
      REFERENCES ASIGNATURA_PERIODO (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA, COD_PERIODO_LECTIVO, COD_PARALELO, COD_DOCENTE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASIGNATURA ADD CONSTRAINT FK_ASIGNATU_ASIGANTUR_NIVEL_ED FOREIGN KEY (COD_NIVEL_EDUCATIVO)
      REFERENCES NIVEL_EDUCATIVO (COD_NIVEL_EDUCATIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASIGNATURA_PERIODO ADD CONSTRAINT FK_ASIGNATU_REFERENCE_ASIGNATU FOREIGN KEY (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA)
      REFERENCES ASIGNATURA (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASIGNATURA_PERIODO ADD CONSTRAINT FK_ASIGNATU_REFERENCE_PERIODO_ FOREIGN KEY (COD_PERIODO_LECTIVO)
      REFERENCES PERIODO_LECTIVO (COD_PERIODO_LECTIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASIGNATURA_PERIODO ADD CONSTRAINT FK_ASIGNATU_REFERENCE_PARALELO FOREIGN KEY (COD_PARALELO)
      REFERENCES PARALELO (COD_PARALELO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASIGNATURA_PERIODO ADD CONSTRAINT FK_ASIGNATU_REFERENCE_PERSONA FOREIGN KEY (COD_DOCENTE)
      REFERENCES PERSONA (COD_PERSONA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASISTENCIA_PERIODO ADD CONSTRAINT FK_ASISTENC_REFERENCE_MATRICUL FOREIGN KEY (COD_PERIODO_LECTIVO, COD_ALUMNO, COD_NIVEL_EDUCATIVO)
      REFERENCES MATRICULA_PERIODO (COD_PERIODO_LECTIVO, COD_ALUMNO, COD_NIVEL_EDUCATIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE AULA ADD CONSTRAINT FK_AULA_AULA_A_ED_EDIFICIO FOREIGN KEY (COD_EDIFICIO)
      REFERENCES EDIFICIO (COD_EDIFICIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CALIFICACION_PRUEBA_ASPIRANTE ADD CONSTRAINT FK_CALIFICA_ASPIRANTE_ASPIRANT FOREIGN KEY (COD_ASPIRANTE)
      REFERENCES ASPIRANTE (COD_ASPIRANTE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CALIFICACION_PRUEBA_ASPIRANTE ADD CONSTRAINT FK_CALIFICA_NIVEL_EDU_NIVEL_ED FOREIGN KEY (COD_NIVEL_EDUCATIVO)
      REFERENCES NIVEL_EDUCATIVO (COD_NIVEL_EDUCATIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COMUNICADO_ASIGNATURA ADD CONSTRAINT FK_COMUNICA_REFERENCE_ASIGNATU FOREIGN KEY (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA, COD_PERIODO_LECTIVO, COD_PARALELO, COD_DOCENTE)
      REFERENCES ASIGNATURA_PERIODO (COD_NIVEL_EDUCATIVO, COD_ASIGNATURA, COD_PERIODO_LECTIVO, COD_PARALELO, COD_DOCENTE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CRONOGRAMA_PERIODO ADD CONSTRAINT FK_CRONOGRA_CRONOGRAM_PERIODO_ FOREIGN KEY (COD_PERIODO_LECTIVO)
      REFERENCES PERIODO_LECTIVO (COD_PERIODO_LECTIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE EDIFICIO ADD CONSTRAINT FK_EDIFICIO_EDIFICIO__SEDE FOREIGN KEY (COD_SEDE)
      REFERENCES SEDE (COD_SEDE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATRICULA_PERIODO ADD CONSTRAINT FK_MATRICUL_REFERENCE_PERIODO_ FOREIGN KEY (COD_PERIODO_LECTIVO)
      REFERENCES PERIODO_LECTIVO (COD_PERIODO_LECTIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATRICULA_PERIODO ADD CONSTRAINT FK_MATRICUL_REFERENCE_PERSONA FOREIGN KEY (COD_ALUMNO)
      REFERENCES PERSONA (COD_PERSONA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATRICULA_PERIODO ADD CONSTRAINT FK_MATRICUL_REFERENCE_NIVEL_ED FOREIGN KEY (COD_NIVEL_EDUCATIVO)
      REFERENCES NIVEL_EDUCATIVO (COD_NIVEL_EDUCATIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PARALELO ADD CONSTRAINT FK_PARALELO_REFERENCE_NIVEL_ED FOREIGN KEY (COD_NIVEL_EDUCATIVO)
      REFERENCES NIVEL_EDUCATIVO (COD_NIVEL_EDUCATIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_PERSONA_A_PERSONA FOREIGN KEY (COD_PERSONA_REPRESENTANTE)
      REFERENCES PERSONA (COD_PERSONA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE REGLA_PERIODO ADD CONSTRAINT FK_REGLA_PE_REGLAPER__PERIODO_ FOREIGN KEY (COD_PERIODO_LECTIVO)
      REFERENCES PERIODO_LECTIVO (COD_PERIODO_LECTIVO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ROL_USUARIO ADD CONSTRAINT FK_ROL_USUA_ROLUSU_A__ROL FOREIGN KEY (COD_ROL)
      REFERENCES ROL (COD_ROL) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ROL_USUARIO ADD CONSTRAINT FK_ROL_USUA_ROLUSU_A__USUARIO FOREIGN KEY (COD_USUARIO)
      REFERENCES USUARIO (COD_USUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TIPO_PERSONA_PERSONA ADD CONSTRAINT FK_TIPO_PER_TIPOPERPE_TIPO_PER FOREIGN KEY (COD_TIPO_PERSONA)
      REFERENCES TIPO_PERSONA (COD_TIPO_PERSONA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TIPO_PERSONA_PERSONA ADD CONSTRAINT FK_TIPO_PER_TIPOPER_A_PERSONA FOREIGN KEY (COD_PERSONA)
      REFERENCES PERSONA (COD_PERSONA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_USUARIO_A_PERSONA FOREIGN KEY (COD_PERSONA)
      REFERENCES PERSONA (COD_PERSONA) ON DELETE RESTRICT ON UPDATE RESTRICT;
